[package]
name = "propolis-server-api"
version = "0.1.0"
license = "MPL-2.0"
edition = "2024"

[dependencies]
crucible-client-types.workspace = true
dropshot.workspace = true
dropshot-api-manager-types.workspace = true
propolis_api_types.workspace = true
