[alias]
xtask = "run --package xtask --quiet --"
phd = "run --package cargo-phd --quiet --"

[env]
# Currently required by Falcon due to
# https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
CARGO_WORKSPACE_DIR = { value = "", relative = true }
