[package]
name = "propolis-mock-server"
version = "0.0.0"
license = "MPL-2.0"
edition = "2021"

[lib]
name = "propolis_mock_server"
path = "src/lib/lib.rs"
doc = false
doctest = false
test = false

[[bin]]
name = "propolis-mock-server"
path = "src/main.rs"
doc = false
doctest = false
test = false

[dependencies]
atty.workspace = true
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
base64.workspace = true
dropshot = { workspace = true }
futures.workspace = true
hyper.workspace = true
serde.workspace = true
propolis_api_types.workspace = true
propolis_types.workspace = true
semver.workspace = true
serde_json.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-dtrace.workspace = true
slog-term.workspace = true
slog-bunyan.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite.workspace = true

# Progenitor is used to instantiate copies of the API types without exposing
# internal dependencies (like crucible-client-types).  Although we are not
# using the client itself, its deps (reqwest, etc) are required.
progenitor.workspace = true
reqwest.workspace = true
schemars.workspace = true
rand.workspace = true
uuid.workspace = true
