[package.propolis-server]
service_name = "propolis-server"
source.type = "local"
source.rust.binary_names = ["propolis-server"]
source.rust.release = true
source.paths = [
    { from = "packaging/smf/propolis-server", to = "/var/svc/manifest/site/propolis-server" },
    { from = "packaging/smf/method_script.sh", to = "/opt/oxide/lib/svc/manifest/propolis/propolis.sh" },
]
source.blobs = [ "alpine.iso" ]
output.type = "zone"

# N.B. Should be kept in sync with phd-tests/artifacts.toml.
[[package.propolis-server.source.buildomat_blobs]]
repo = "edk2"
series = "image_debug"
commit = "bf64f45b1a58e69d126a3c6ca1e4512c88668132"
artifact = "OVMF_CODE.fd"
sha256 = "740187046a7267d0de72d3455070333547dbc0ea023531471fb2b2a61effa448"
