#!/bin/bash
set -e

# The ref that headers should be checked against.
#
# This should almost certainly be `stlouis`, as in the "stlouis" branch in the
# Oxide fork of illumos. You may want to change this for testing or development
# if your changes to Propolis track changes in the OS as well.
#
# As a default this ref should probably not change.
HEADER_CHECK_REF="stlouis"

# Directories with `ctest2`-based `header-check` crates. This list should track
# the similar exclusions in `Cargo.toml`, and are described more there.
HEADER_CHECK_DIRS=(
  crates/bhyve-api/header-check/
  crates/nvpair/header-check/
  crates/viona-api/header-check/
)

function usage() {
  SCRIPTNAME="${0##*/}"
  echo "usage:"
  echo "  $SCRIPTNAME run <gate_src_dir>"
  echo "      run Propolis header-check tests against the provided gate checkout"
  echo "  $SCRIPTNAME gate_ref"
  echo "      print the illumos-gate ref headers should be checked against"
}

function run_checks() {
  export GATE_SRC="$(readlink -e $1)"

  if ! [ -d "$GATE_SRC" ]; then
    echo "header-check was given non-existent \"$GATE_SRC\" as gate directory"
    exit 1
  fi

  for checkdir in "${HEADER_CHECK_DIRS[@]}"; do
    echo "RUNNING HEADER-CHECK FOR $checkdir"
    (cd "$checkdir"; GATE_SRC="$GATE_SRC" cargo test)
  done
}

OP="$1"

if [ -z "$1" ]; then
  usage
  exit 1;
fi

case "$OP" in
  "gate_ref" )
    echo "$HEADER_CHECK_REF"
    ;;
  "run" )
    GATE_DIR="$2"
    run_checks "$GATE_DIR"
    ;;
  * )
    usage
    exit 1
    ;;
esac
