[package]
name = "bhyve_api"
version = "0.0.0"
license = "MPL-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc.workspace = true
bhyve_api_sys.workspace = true
num_enum.workspace = true
