[package]
name = "propolis-utils"
version = "0.0.0"
license = "MPL-2.0"
edition = "2021"

[[bin]]
name = "cpuid-gen"
test = false
doctest = false

[[bin]]
name = "rsrvrctl"
test = false
doctest = false

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
propolis = { workspace = true, default-features = false }
propolis_api_types.workspace = true
bhyve_api = { workspace = true }
libc = { workspace = true }
serde_json.workspace = true
