// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Generates a DSDT and SSDT ACPI tables for an instance.
//!
//! The [`Dsdt`] struct implements the `Aml` trait of the `acpi_tables` crate
//! and can write the AML bytecode to any AmlSink, like a `Vec<u8>`.
//!
//! The AML code can also be generated by the objects being represented in the
//! DSDT table, which is often a better practice as it keeps internal
//! configuration and AML representation close to each other.
//!
//! Structs that implement the [`DsdtGenerator`] trait can be passed to
//! [`DsdtConfig`] and their AML code will be added to the scope they selected.

// XXX(acpi): Most of the DSDT and SSDT tables are generated here to keep them
//            consistent with the original EDK2 static tables. In the future
//            they could be created by the devices they represent. For example,
//            the _SB scope can be created by the I440FxHostBridge struct, the
//            LPC by Piix3Lpc etc., but they currently lack all the information
//            necessary to generate the tables. This pattern is already used
//            for some devices when possible.
// https://github.com/oxidecomputer/edk2/blob/f33871f488bfbbc080e0f7e3881e04d0db0b6367/OvmfPkg/AcpiTables/Dsdt.asl

use super::{
    GPE0_BLK_ADDR, GPE0_BLK_LEN, IO_APIC_ADDR, LOCAL_APIC_ADDR,
    PCI_HOTPLUG_STATUS_ADDR, PCI_HOTPLUG_STATUS_LEN, PCI_LINK_IRQS,
    PM1A_EVT_BLK_ADDR, SCI_IRQ,
};
use acpi_tables::{aml, sdt::Sdt, Aml, AmlSink};

/// The ACPI scope in which DsdtGenerators are placed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DsdtScope {
    SystemBus, // \_SB scope.
    PciRoot,   // \_SB.PCI0 scope.
    Lpc,       // \_SB.PCI0.LPC scope.
}

/// An implementer of DsdtGenerator is able to generate AML code to be loaded
/// into the DSDT ACPI table.
pub trait DsdtGenerator: Aml {
    /// Returns the scope of the DSDT table in which the generated AML code
    /// should be placed.
    fn dsdt_scope(&self) -> DsdtScope;
}

/// Wraps a list of DsdtGenerators to help generate their AML code in places
/// where a `&dyn Aml` is needed.
struct DsdtGeneratorAml<'a> {
    generators: &'a [&'a dyn DsdtGenerator],
    scope: DsdtScope,
}

impl<'a> DsdtGeneratorAml<'a> {
    fn new(generators: &'a [&'a dyn DsdtGenerator], scope: DsdtScope) -> Self {
        Self { generators, scope }
    }
}

impl<'a> Aml for DsdtGeneratorAml<'a> {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        self.generators
            .iter()
            .filter(|&&g| g.dsdt_scope() == self.scope)
            .for_each(|&g| g.to_aml_bytes(sink));
    }
}

/// Values for the PM1a_CNT.SLP_TYP register to enter different sleep states.
///
/// <https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/07_Power_and_Performance_Mgmt/oem-supplied-system-level-control-methods.html?highlight=_sx#sx-system-states>
const PM1A_CNT_SLP_TYP_S0: u8 = 5;
const PM1A_CNT_SLP_TYP_S3: u8 = 1;
const PM1A_CNT_SLP_TYP_S4: u8 = 2;
const PM1A_CNT_SLP_TYP_S5: u8 = 0;

pub struct DsdtConfig<'a> {
    pub generators: &'a [&'a dyn DsdtGenerator],
}

/// The DSDT table is part of the fixed ACPI tables and is used to describe
/// system resources.
///
/// <https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html#differentiated-system-description-table-dsdt>
pub struct Dsdt<'a> {
    config: DsdtConfig<'a>,
}

impl<'a> Dsdt<'a> {
    pub fn new(config: DsdtConfig<'a>) -> Self {
        Self { config }
    }
}

impl<'a> Aml for Dsdt<'a> {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        let mut dsdt = Vec::new();

        // XXX(acpi): This is an artifact inserted into the AML code to keep
        //            the DSDT table exactly the same as the static EDK2 tables
        //            used previously. It's not functionally necessary.
        aml::If::new(
            &aml::ZERO,
            vec![&aml::External::new(
                "\\_SB_.PCI0._CRS.FWDT".into(),
                aml::ExternalObjectType::OperationRegion,
                None,
            )],
        )
        .to_aml_bytes(&mut dsdt);

        // Sleep states.
        SleepState::new("_S0_", PM1A_CNT_SLP_TYP_S0).to_aml_bytes(&mut dsdt);
        SleepState::new("_S5_", PM1A_CNT_SLP_TYP_S5).to_aml_bytes(&mut dsdt);

        // System bus namespace (\_SB).
        aml::Scope::new(
            "_SB_".into(),
            vec![
                &PciRootBridge { generators: self.config.generators },
                &DsdtGeneratorAml::new(
                    self.config.generators,
                    DsdtScope::SystemBus,
                ),
            ],
        )
        .to_aml_bytes(&mut dsdt);

        // DSDT table.
        // XXX(acpi): OEM ID, table ID, and revision are kept the same as the
        //            original static EDK2 tables for consistency. They could
        //            be set to Propolis-specific values in the future.
        let mut sdt = Sdt::new(*b"DSDT", 36, 1, *b"INTEL ", *b"OVMF    ", 0x4);
        sdt.append_slice(dsdt.as_slice());
        sdt.to_aml_bytes(sink);
    }
}

/// Describe a sleep state.
struct SleepState<'a> {
    state: &'a str,
    pm1a_cnt: u8,
}

impl<'a> SleepState<'a> {
    fn new(state: &'a str, pm1a_cnt: u8) -> Self {
        Self { state, pm1a_cnt }
    }
}

impl<'a> Aml for SleepState<'a> {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        aml::Name::new(
            self.state.into(),
            &aml::Package::new(vec![
                &self.pm1a_cnt, // PM1a_CNT.SLP_TYP value to enter this sleep state.
                &aml::ZERO, // PM1b_CNT.SLP_TYP value. PM1b is not currently used in Propolis.
                &aml::ZERO, // Reserved.
                &aml::ZERO, // Reserved.
            ]),
        )
        .to_aml_bytes(sink);
    }
}

/// PCI root bridge namespace (\_SB.PCI0).
struct PciRootBridge<'a> {
    generators: &'a [&'a dyn DsdtGenerator],
}

impl<'a> Aml for PciRootBridge<'a> {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        aml::Device::new(
            "PCI0".into(),
            vec![
                &aml::Name::new("_HID".into(), &aml::EISAName::new("PNP0A03")),
                &aml::Name::new("_ADR".into(), &aml::ZERO),
                &aml::Name::new("_BBN".into(), &aml::ZERO),
                &aml::Name::new("_UID".into(), &aml::ZERO),
                &PciRootBridgeCrs {},
                &PciRootBridgePrt {},
                &PciRootBridgeLpc { generators: self.generators },
                &DsdtGeneratorAml::new(self.generators, DsdtScope::PciRoot),
            ],
        )
        .to_aml_bytes(sink);
    }
}

/// I/O port range for PCI configuration.
///
/// <https://wiki.osdev.org/PCI#Configuration_Space_Access_Mechanism_#1>
const PCI_CONFIG_IO_BASE: u16 = 0x0cf8;
const PCI_CONFIG_IO_SIZE: u8 = 8;

/// Bus number range for the PCI0 root bridge.
const PCI_BUS_START: u16 = 0x00;
const PCI_BUS_END: u16 = 0xff;

/// MMIO address region used for legacy VGA devices.
///
/// <https://en.wikipedia.org/wiki/Video_Graphics_Array#Use>
const LEGACY_VGA_BASE: u32 = 0x000a_0000;
const LEGACY_VGA_LIMIT: u32 = 0x000b_ffff;

// Byte offset for different fields that are referenced by other structures.
const ADDRESS_SPACE_32_MIN_OFFSET: usize = 0x0a;
const ADDRESS_SPACE_32_MAX_OFFSET: usize = 0x0e;
const ADDRESS_SPACE_32_LEN_OFFSET: usize = 0x16;

const ADDRESS_SPACE_64_MIN_OFFSET: usize = 0x0e;
const ADDRESS_SPACE_64_MAX_OFFSET: usize = 0x16;
const ADDRESS_SPACE_64_LEN_OFFSET: usize = 0x26;

const INTERRUPT_LIST_OFFSET: usize = 0x05;

/// _CRS method for the PCI0 device (\_SB.PCI0._CRS).
///
/// Refer to section 4.3 of the PCI Firmware Specification for more
/// information.
struct PciRootBridgeCrs {}

// XXX(acpi): This implementation currently follows the original static EDK2
//            tables. It can be simplified to return a single ResourceTemplate
//            with all final values already populated instead of dynamically
//            updating them based on the values from FWDT.
impl Aml for PciRootBridgeCrs {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        // \_SB.PCI0.CRES
        //
        // This ResourceTemplate contains the base values for the PCI I/O ports
        // and MMIO region reservations.
        let mut cres: Vec<&dyn Aml> = Vec::new();

        // PCI device numbers that belong to this bridge.
        let bus_number =
            aml::AddressSpace::new_bus_number(PCI_BUS_START, PCI_BUS_END);
        cres.push(&bus_number);

        // Legacy PCI configuration I/O ports.
        let pci_config_io_ports = aml::IO::new(
            PCI_CONFIG_IO_BASE,
            PCI_CONFIG_IO_BASE,
            1,
            PCI_CONFIG_IO_SIZE,
        );
        cres.push(&pci_config_io_ports);

        // I/O ports below the PCI config ports (0x0000-0x0cf7).
        let pci_io_ports_low =
            aml::AddressSpace::new_io(0x0000, PCI_CONFIG_IO_BASE - 1, None);
        cres.push(&pci_io_ports_low);

        // IO ports above the PCI config ports (0x0d00-0xffff).
        let pci_io_ports_high = aml::AddressSpace::new_io(
            PCI_CONFIG_IO_BASE + PCI_CONFIG_IO_SIZE as u16,
            0xffff,
            None,
        );
        cres.push(&pci_io_ports_high);

        // Legacy VGA MMIO region.
        let legacy_vga = aml::AddressSpace::new_memory(
            aml::AddressSpaceCacheable::Cacheable,
            true,
            LEGACY_VGA_BASE,
            LEGACY_VGA_LIMIT,
            None,
        );
        cres.push(&legacy_vga);

        // The _CRS method needs to reference the 32-bit PCI MMIO region to
        // update its range based on the instance configuration. The reference
        // is based on the byte offset of this AddressSpace inside the CRES
        // ResourceTemplate.
        let mmio32_offset = aml_len(&cres);
        let mmio32 = aml::AddressSpace::new_memory(
            aml::AddressSpaceCacheable::NotCacheable,
            true,
            0xf800_0000_u32, // Value overwritten by _CRS.
            0xfffb_ffff_u32, // Value overwritten by _CRS.
            None,
        );
        cres.push(&mmio32);

        aml::Name::new("CRES".into(), &aml::ResourceTemplate::new(cres))
            .to_aml_bytes(sink);

        // \_SB.PCI0.CR64
        //
        // This ResourceTemplate contains the 64-bit PCI MMIO region. The _CRS
        // method concatenates it with CRES, if necessary, based on the
        // instance configuration.
        let mut cr64: Vec<&dyn Aml> = Vec::new();

        // The _CRS method needs to reference the 64-bit PCI MMIO region to
        // update its range based on the instance configuration. The reference
        // is based on the byte offset of this AddressSpace inside the CR64
        // ResourceTemplate.
        let mmio64_offset = aml_len(&cr64);
        let mmio64 = aml::AddressSpace::new_memory(
            aml::AddressSpaceCacheable::Cacheable,
            true,
            0x0080_0000_0000_u64, // Value overwritten by _CRS.
            0x0fff_ffff_ffff_u64, // Value overwritten by _CRS.
            None,
        );
        cr64.push(&mmio64);

        aml::Name::new("CR64".into(), &aml::ResourceTemplate::new(cr64))
            .to_aml_bytes(sink);

        // \_SB.PCI0._CRS
        //
        // This method returns a ResourceTemplate describing the PCI root
        // bridge resources.
        //
        // It reads the FWDT OperationRegion that is declared in the SSDT. This
        // region is populated by Propolis in lib/propolis/src/hw/qemu/fwcfg.rs
        // and it stores the 32-bit and 64-bit MMIO regions reserved for PCI
        // devices.
        aml::Method::new(
            "_CRS".into(),
            0,
            true,
            vec![
                // Create references to values in the FWDT OperationRegion.
                &aml::Field::new(
                    "FWDT".into(),
                    aml::FieldAccessType::QWord,
                    aml::FieldLockRule::NoLock,
                    aml::FieldUpdateRule::Preserve,
                    vec![
                        aml::FieldEntry::Named(*b"P0S_", 64),
                        aml::FieldEntry::Named(*b"P0E_", 64),
                        aml::FieldEntry::Named(*b"P0L_", 64),
                        aml::FieldEntry::Named(*b"P1S_", 64),
                        aml::FieldEntry::Named(*b"P1E_", 64),
                        aml::FieldEntry::Named(*b"P1L_", 64),
                    ],
                ),
                &aml::Field::new(
                    "FWDT".into(),
                    aml::FieldAccessType::DWord,
                    aml::FieldLockRule::NoLock,
                    aml::FieldUpdateRule::Preserve,
                    vec![
                        aml::FieldEntry::Named(*b"P0SL", 32),
                        aml::FieldEntry::Named(*b"P0SH", 32),
                        aml::FieldEntry::Named(*b"P0EL", 32),
                        aml::FieldEntry::Named(*b"P0EH", 32),
                        aml::FieldEntry::Named(*b"P0LL", 32),
                        aml::FieldEntry::Named(*b"P0LH", 32),
                        aml::FieldEntry::Named(*b"P1SL", 32),
                        aml::FieldEntry::Named(*b"P1SH", 32),
                        aml::FieldEntry::Named(*b"P1EL", 32),
                        aml::FieldEntry::Named(*b"P1EH", 32),
                        aml::FieldEntry::Named(*b"P1LL", 32),
                        aml::FieldEntry::Named(*b"P1LH", 32),
                    ],
                ),
                // Create references to values in the mmio32 AddressSpace.
                &aml::CreateDWordField::new(
                    &aml::Path::new("PS32"),
                    &aml::Path::new("CRES"),
                    &(mmio32_offset + ADDRESS_SPACE_32_MIN_OFFSET),
                ),
                &aml::CreateDWordField::new(
                    &aml::Path::new("PE32"),
                    &aml::Path::new("CRES"),
                    &(mmio32_offset + ADDRESS_SPACE_32_MAX_OFFSET),
                ),
                &aml::CreateDWordField::new(
                    &aml::Path::new("PL32"),
                    &aml::Path::new("CRES"),
                    &(mmio32_offset + ADDRESS_SPACE_32_LEN_OFFSET),
                ),
                // Update the values of mmio32 based on the FWDT.
                &aml::Store::new(
                    &aml::Path::new("PS32"), // mmio32.min
                    &aml::Path::new("P0SL"), // FWDT.32bit.min (low bits)
                ),
                &aml::Store::new(
                    &aml::Path::new("PE32"), // mmio32.max
                    &aml::Path::new("P0EL"), // FWDT.32bit.max (low bits)
                ),
                &aml::Store::new(
                    &aml::Path::new("PL32"), // mmo32.len
                    &aml::Path::new("P0LL"), // FWDT.32bit.len (low bits)
                ),
                // Check if a 64-bit MMIO region is needed.
                &aml::If::new(
                    &aml::LogicalAnd::new(
                        &aml::Equal::new(
                            &aml::Path::new("P1SL"), // FWDT.64bit.min (low bits)
                            &aml::ZERO,
                        ),
                        &aml::Equal::new(
                            &aml::Path::new("P1SH"), // FWDT.64bit.min (high bits)
                            &aml::ZERO,
                        ),
                    ),
                    // Only use CRES if FWDT.64bit.min is zero...
                    vec![&aml::Return::new(&aml::Path::new("CRES"))],
                ),
                // ...otherwise concatenate CRES and CR64.
                &aml::Else::new(vec![
                    // Create references to values in the mmio64 AddressSpace.
                    &aml::CreateQWordField::new(
                        &aml::Path::new("PS64"),
                        &aml::Path::new("CR64"),
                        &(mmio64_offset + ADDRESS_SPACE_64_MIN_OFFSET),
                    ),
                    &aml::CreateQWordField::new(
                        &aml::Path::new("PE64"),
                        &aml::Path::new("CR64"),
                        &(mmio64_offset + ADDRESS_SPACE_64_MAX_OFFSET),
                    ),
                    &aml::CreateQWordField::new(
                        &aml::Path::new("PL64"),
                        &aml::Path::new("CR64"),
                        &(mmio64_offset + ADDRESS_SPACE_64_LEN_OFFSET),
                    ),
                    // Update the values of mmio64 based on the FWDT.
                    &aml::Store::new(
                        &aml::Path::new("PS64"), // mmio64.min
                        &aml::Path::new("P1S_"), // FWDT.64bit.min
                    ),
                    &aml::Store::new(
                        &aml::Path::new("PE64"), // mmio64.max
                        &aml::Path::new("P1E_"), // FWDT.64bit.max
                    ),
                    &aml::Store::new(
                        &aml::Path::new("PL64"), // mmio64.max
                        &aml::Path::new("P1L_"), // FWDT.64bit.max
                    ),
                    // Concatenate CRES and CR64.
                    &aml::ConcatRes::new(
                        &aml::Local(0),
                        &aml::Path::new("CRES"),
                        &aml::Path::new("CR64"),
                    ),
                    &aml::Return::new(&aml::Local(0)),
                ]),
            ],
        )
        .to_aml_bytes(sink);
    }
}

fn aml_len(vec: &[&dyn Aml]) -> usize {
    let mut sink = Vec::new();
    for aml in vec {
        aml.to_aml_bytes(&mut sink);
    }
    sink.len()
}

/// Number of devices in the PCI0 root bridge.
// XXX(acpi): Value inherited from the original EDK2 static tables. It should
//            be updated to match Propolis's expectations.
const PCI_DEVICES: u8 = 16;
const PCI_INT_PINS: u8 = 4;

/// _PRT method for the PCI0 device (\_SB.PCI0._PRT)
///
/// <https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/06_Device_Configuration/Device_Configuration.html?highlight=_prt#prt-pci-routing-table>
struct PciRootBridgePrt {}

impl Aml for PciRootBridgePrt {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        let sources = ["^LPC_.LNKA", "^LPC_.LNKB", "^LPC_.LNKC", "^LPC_.LNKD"];
        let sources_len: u8 = sources.len() as u8;

        let mut ptr_entries = Vec::new();
        for device in 0..PCI_DEVICES {
            for pin in 0..PCI_INT_PINS {
                let source = if device == 1 && pin == 0 {
                    // Device 1, Pin 0 requires special handling.
                    // https://github.com/oxidecomputer/edk2/blob/f33871f488bfbbc080e0f7e3881e04d0db0b6367/OvmfPkg/AcpiTables/Dsdt.asl#L200-L220
                    "^LPC_.LNKS"
                } else {
                    // PCI devices are connected in a crossing pattern to
                    // evenly distribute load across the interrupt lines.
                    //
                    //                      ┌──────────┐     ┌──────────┐     ┌──────────┐
                    //                      │PCI Device│     │PCI Device│     │PCI Device│
                    //                      │    #1    │     │    #2    │     │    #3    │
                    // ┌───────────────┐    │          │     │          │     │          │
                    // │    IO/APIC    │    │   INTA   │     │          │     │          │
                    // │               │┌───┼────*─────┼┐┌───┼────*─────┼┐┌───┼────*─────┼─--
                    // │          LNKA ├┼──┐│   INTB   │││   │          │││   │          │
                    // │          LNKB ├┼─┐└┼────*─────┼┼┘┌──┼────*─────┼┼┘┌──┼────*─────┼─--
                    // │          LNKC ├┼┐│ │   INTC   ││ │  │          ││ │  │          │
                    // │          LNKD ├┘│└─┼────*─────┼┼─┘┌─┼────*─────┼┼─┘┌─┼────*─────┼─--
                    // └───────────────┘ │  │   INTD   ││  │ │          ││  │ │          │
                    //                   └──┼────*─────┼┼──┘┌┼────*─────┼┼──┘┌┼────*─────┼─--
                    //                      └──────────┘└───┘└──────────┘└───┘└──────────┘
                    //
                    let idx = (device + pin + sources_len - 1) % sources_len;
                    sources[idx as usize]
                };

                ptr_entries.push(PrtEntry { device, pin, source });
            }
        }
        let ptr = ptr_entries.iter().map(|p| p as &dyn Aml).collect();

        aml::Method::new(
            "_PRT".into(),
            0,
            false,
            vec![&aml::Return::new(&aml::Package::new(ptr))],
        )
        .to_aml_bytes(sink);
    }
}

/// Low-word of an _ADR value that refers to all PCI functions.
///
/// <https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/06_Device_Configuration/Device_Configuration.html#adr-object-address-encodings>
const PCI_ADR_ALL_FUNC: u32 = 0xffff;

/// Representation of an entry in the _PRT table.
struct PrtEntry<'a> {
    device: u8,
    pin: u8,
    source: &'a str,
}

impl<'a> Aml for PrtEntry<'a> {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        let addr: aml::DWord = ((self.device as u32) << 16) | PCI_ADR_ALL_FUNC;

        aml::Package::new(vec![
            &addr,
            &self.pin,
            &aml::Path::new(self.source),
            &aml::ZERO,
        ])
        .to_aml_bytes(sink);
    }
}

/// PCI to ISA bridge for the PCI0 device (\_SB.PCI0.LPC).
///
/// Refer to the original _PRT table from EDK2 for more details on what is being
/// defined here.
///
/// <https://github.com/oxidecomputer/edk2/blob/f33871f488bfbbc080e0f7e3881e04d0db0b6367/OvmfPkg/AcpiTables/Dsdt.asl#L299-L303>
struct PciRootBridgeLpc<'a> {
    generators: &'a [&'a dyn DsdtGenerator],
}

// XXX(acpi): This table is currently kept the same as the original EDK2 static
//            table, but it could be modernized to remove devices that are not
//            used in a virtual machine environment.
impl<'a> Aml for PciRootBridgeLpc<'a> {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        aml::Device::new(
            "LPC_".into(),
            vec![
                &aml::Name::new("_ADR".into(), &0x0001_0000_u64),
                &Lnk::new("LNKS", 0),
                // PCI Interrupt Routing Configuration Registers, PIRQRC[A:D].
                &aml::OpRegion::new(
                    "PRR0".into(),
                    aml::OpRegionSpace::PCIConfig,
                    &0x60_u64,
                    &0x04_u64,
                ),
                &aml::Field::new(
                    "PRR0".into(),
                    aml::FieldAccessType::Any,
                    aml::FieldLockRule::NoLock,
                    aml::FieldUpdateRule::Preserve,
                    vec![
                        aml::FieldEntry::Named(*b"PIRA", 8),
                        aml::FieldEntry::Named(*b"PIRB", 8),
                        aml::FieldEntry::Named(*b"PIRC", 8),
                        aml::FieldEntry::Named(*b"PIRD", 8),
                    ],
                ),
                // _STA method for LNKA, LNKB, LNKC, and LNKD.
                &aml::Method::new(
                    "PSTA".into(),
                    1,
                    false,
                    vec![
                        &aml::If::new(
                            &aml::And::new(&aml::ZERO, &aml::Arg(0), &0x80_u64),
                            vec![&aml::Return::new(&0x09_u64)],
                        ),
                        &aml::Else::new(vec![&aml::Return::new(&0x0B_u64)]),
                    ],
                ),
                // _CRS method for LNKA, LNKB, LNKC, and LNKD.
                &aml::Method::new(
                    "PCRS".into(),
                    1,
                    true,
                    vec![
                        &aml::Name::new(
                            "BUF0".into(),
                            &aml::ResourceTemplate::new(vec![
                                &aml::Interrupt::new(
                                    true,
                                    false,
                                    false,
                                    true,
                                    vec![0x00],
                                ),
                            ]),
                        ),
                        &aml::CreateDWordField::new(
                            &aml::Path::new("IRQW"),
                            &aml::Path::new("BUF0"),
                            &INTERRUPT_LIST_OFFSET,
                        ),
                        &aml::If::new(
                            &aml::LogicalNot::new(&aml::And::new(
                                &aml::ZERO,
                                &aml::Arg(0),
                                &0x80_u64,
                            )),
                            vec![&aml::Store::new(
                                &aml::Path::new("IRQW"),
                                &aml::Arg(0),
                            )],
                        ),
                        &aml::Return::new(&aml::Path::new("BUF0")),
                    ],
                ),
                // _PRS resource for LNKA, LNKB, LNKC, and LNKD.
                &aml::Name::new(
                    "PPRS".into(),
                    &aml::ResourceTemplate::new(vec![&aml::Interrupt::new(
                        true,
                        false,
                        false,
                        true,
                        PCI_LINK_IRQS
                            .iter()
                            .filter(|i| **i != SCI_IRQ) // The SCI has special handling LNKS.
                            .map(|i| *i as u32)
                            .collect(),
                    )]),
                ),
                &Lnk::new("LNKA", 1),
                &Lnk::new("LNKB", 2),
                &Lnk::new("LNKC", 3),
                &Lnk::new("LNKD", 4),
                // Programmable Interrupt Controller (PIC).
                &aml::Device::new(
                    "PIC_".into(),
                    vec![
                        &aml::Name::new(
                            "_HID".into(),
                            &aml::EISAName::new("PNP0000"),
                        ),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![
                                &aml::IO::new(0x0020, 0x0020, 0x00, 0x02),
                                &aml::IO::new(0x00A0, 0x00A0, 0x00, 0x02),
                                &aml::IO::new(0x04d0, 0x04d0, 0x00, 0x02),
                                &aml::IrqNoFlags::new(2),
                            ]),
                        ),
                    ],
                ),
                // ISA DMA.
                &aml::Device::new(
                    "DMAC".into(),
                    vec![
                        &aml::Name::new(
                            "_HID".into(),
                            &aml::EISAName::new("PNP0200"),
                        ),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![
                                &aml::IO::new(0x0000, 0x0000, 0x00, 0x10),
                                &aml::IO::new(0x0081, 0x0081, 0x00, 0x03),
                                &aml::IO::new(0x0087, 0x0087, 0x00, 0x01),
                                &aml::IO::new(0x0089, 0x0089, 0x00, 0x03),
                                &aml::IO::new(0x008f, 0x008f, 0x00, 0x01),
                                &aml::IO::new(0x00c0, 0x00c0, 0x00, 0x20),
                                &aml::Dma::new(
                                    aml::DmaChannelSpeed::Compatibility,
                                    aml::DmaMasterStatus::NotMaster,
                                    aml::DmaTransferType::Transfer8,
                                    vec![4],
                                ),
                            ]),
                        ),
                    ],
                ),
                // 8254 Timer.
                &aml::Device::new(
                    "TMR_".into(),
                    vec![
                        &aml::Name::new(
                            "_HID".into(),
                            &aml::EISAName::new("PNP0100"),
                        ),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![
                                &aml::IO::new(0x0040, 0x0040, 0x00, 0x04),
                                &aml::IrqNoFlags::new(0),
                            ]),
                        ),
                    ],
                ),
                // Real Time Clock.
                &aml::Device::new(
                    "RTC_".into(),
                    vec![
                        &aml::Name::new(
                            "_HID".into(),
                            &aml::EISAName::new("PNP0B00"),
                        ),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![
                                &aml::IO::new(0x0070, 0x0070, 0x00, 0x02),
                                &aml::IrqNoFlags::new(8),
                            ]),
                        ),
                    ],
                ),
                // PCAT Speaker.
                &aml::Device::new(
                    "SPKR".into(),
                    vec![
                        &aml::Name::new(
                            "_HID".into(),
                            &aml::EISAName::new("PNP0800"),
                        ),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![&aml::IO::new(
                                0x0061, 0x0061, 0x01, 0x01,
                            )]),
                        ),
                    ],
                ),
                // Floating Point Coprocessor.
                &aml::Device::new(
                    "FPU_".into(),
                    vec![
                        &aml::Name::new(
                            "_HID".into(),
                            &aml::EISAName::new("PNP0C04"),
                        ),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![
                                &aml::IO::new(0x00f0, 0x00f0, 0x00, 0x10),
                                &aml::IrqNoFlags::new(13),
                            ]),
                        ),
                    ],
                ),
                // Generic motherboard devices and pieces that don't fit
                // anywhere else.
                &aml::Device::new(
                    "XTRA".into(),
                    vec![
                        &aml::Name::new(
                            "_HID".into(),
                            &aml::EISAName::new("PNP0C02"),
                        ),
                        &aml::Name::new("_UID".into(), &aml::ONE),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![
                                &aml::IO::new(0x0010, 0x0010, 0x00, 0x10),
                                &aml::IO::new(0x0022, 0x0022, 0x00, 0x1e),
                                &aml::IO::new(0x0044, 0x0044, 0x00, 0x1c),
                                &aml::IO::new(0x0062, 0x0062, 0x00, 0x02),
                                &aml::IO::new(0x0065, 0x0065, 0x00, 0x0b),
                                &aml::IO::new(0x0072, 0x0072, 0x00, 0x0e),
                                &aml::IO::new(0x0080, 0x0080, 0x00, 0x01),
                                &aml::IO::new(0x0084, 0x0084, 0x00, 0x03),
                                &aml::IO::new(0x0088, 0x0088, 0x00, 0x01),
                                &aml::IO::new(0x008c, 0x008c, 0x00, 0x03),
                                &aml::IO::new(0x0090, 0x0090, 0x00, 0x10),
                                &aml::IO::new(0x00a2, 0x00a2, 0x00, 0x1e),
                                &aml::IO::new(0x00e0, 0x00e0, 0x00, 0x10),
                                &aml::IO::new(0x01e0, 0x01e0, 0x00, 0x10),
                                &aml::IO::new(0x0160, 0x0160, 0x00, 0x10),
                                &aml::IO::new(0x0370, 0x0370, 0x00, 0x02),
                                &aml::IO::new(0x0402, 0x0402, 0x00, 0x01),
                                &aml::IO::new(0x0440, 0x0440, 0x00, 0x10),
                                // QEMU GPE0 BLK.
                                &aml::IO::new(
                                    GPE0_BLK_ADDR,
                                    GPE0_BLK_ADDR,
                                    0x00,
                                    GPE0_BLK_LEN,
                                ),
                                // PMBLK1.
                                &aml::IO::new(
                                    PM1A_EVT_BLK_ADDR,
                                    PM1A_EVT_BLK_ADDR,
                                    0x00,
                                    0x40,
                                ),
                                // IO APIC.
                                &aml::Memory32Fixed::new(
                                    false,
                                    IO_APIC_ADDR,
                                    0x0000_1000,
                                ),
                                // LAPIC.
                                &aml::Memory32Fixed::new(
                                    false,
                                    LOCAL_APIC_ADDR,
                                    0x0010_0000,
                                ),
                            ]),
                        ),
                    ],
                ),
                &DsdtGeneratorAml::new(self.generators, DsdtScope::Lpc),
                // QEMU panic device.
                //
                // XXX(acpi): This code could be generated by the QemuPvpanic
                //            struct and passed as a DsdtGenerator, but it's
                //            only present if the enable_isa configuration is
                //            enabled for the instance. So it's always
                //            generated here for now to maintain consistency
                //            with the original EDK2 static tables.
                &aml::Device::new(
                    "PEVT".into(),
                    vec![
                        &aml::Name::new("_HID".into(), &"QEMU0001"),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![&aml::IO::new(
                                0x0505, 0x0505, 0x01, 0x01,
                            )]),
                        ),
                        &aml::OpRegion::new(
                            "PEOR".into(),
                            aml::OpRegionSpace::SystemIO,
                            &0x0505_u64,
                            &aml::ONE,
                        ),
                        &aml::Field::new(
                            "PEOR".into(),
                            aml::FieldAccessType::Byte,
                            aml::FieldLockRule::NoLock,
                            aml::FieldUpdateRule::Preserve,
                            vec![aml::FieldEntry::Named(*b"PEPT", 8)],
                        ),
                        &aml::Name::new("_STA".into(), &0x0f_u64),
                        &aml::Method::new(
                            "RDPT".into(),
                            0,
                            false,
                            vec![
                                &aml::Store::new(
                                    &aml::Local(0),
                                    &aml::Path::new("PEPT"),
                                ),
                                &aml::Return::new(&aml::Local(0)),
                            ],
                        ),
                        &aml::Method::new(
                            "WRPT".into(),
                            1,
                            false,
                            vec![&aml::Store::new(
                                &aml::Path::new("PEPT"),
                                &aml::Arg(0),
                            )],
                        ),
                    ],
                ),
            ],
        )
        .to_aml_bytes(sink);
    }
}

/// Represents a PCI IRQ link in the LPC device.
struct Lnk<'a> {
    name: &'a str,
    uid: u32,
}

impl<'a> Lnk<'a> {
    fn new(name: &'a str, uid: u32) -> Self {
        Self { name, uid }
    }
}

impl<'a> Lnk<'a> {
    // AML code for the special SCI link.
    // <https://github.com/oxidecomputer/edk2/blob/f33871f488bfbbc080e0f7e3881e04d0db0b6367/OvmfPkg/AcpiTables/Dsdt.asl#L200-L220>
    fn to_aml_bytes_sci(&self, sink: &mut dyn AmlSink) {
        aml::Device::new(
            "LNKS".into(),
            vec![
                &aml::Name::new("_HID".into(), &aml::EISAName::new("PNP0C0F")),
                &aml::Name::new("_UID".into(), &aml::ZERO),
                &aml::Name::new("_STA".into(), &0x0b_u64),
                &aml::Method::new("_SRS".into(), 1, false, vec![]),
                &aml::Method::new("_DIS".into(), 0, false, vec![]),
                &aml::Name::new(
                    "_PRS".into(),
                    &aml::ResourceTemplate::new(vec![&aml::Interrupt::new(
                        true,
                        false,
                        false,
                        true,
                        vec![0x09],
                    )]),
                ),
                &aml::Method::new(
                    "_CRS".into(),
                    0,
                    false,
                    vec![&aml::Return::new(&aml::Path::new("_PRS"))],
                ),
            ],
        )
        .to_aml_bytes(sink);
    }
}

impl<'a> Aml for Lnk<'a> {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        if self.uid == 0 {
            self.to_aml_bytes_sci(sink);
            return;
        }

        let pir = aml::Path::new(&format!(
            "PIR{}",
            self.name.chars().last().unwrap()
        ));

        aml::Device::new(
            aml::Path::new(self.name),
            vec![
                &aml::Name::new("_HID".into(), &aml::EISAName::new("PNP0C0F")),
                &aml::Name::new("_UID".into(), &self.uid),
                &aml::Method::new(
                    "_STA".into(),
                    0,
                    false,
                    vec![&aml::Return::new(&aml::MethodCall::new(
                        "PSTA".into(),
                        vec![&pir],
                    ))],
                ),
                &aml::Method::new(
                    "_DIS".into(),
                    0,
                    false,
                    vec![&aml::Or::new(&pir, &pir, &0x80_u64)],
                ),
                &aml::Method::new(
                    "_CRS".into(),
                    0,
                    false,
                    vec![&aml::Return::new(&aml::MethodCall::new(
                        "PCRS".into(),
                        vec![&pir],
                    ))],
                ),
                &aml::Method::new(
                    "_PRS".into(),
                    0,
                    false,
                    vec![&aml::Return::new(&aml::MethodCall::new(
                        "PPRS".into(),
                        vec![],
                    ))],
                ),
                &aml::Method::new(
                    "_SRS".into(),
                    1,
                    false,
                    vec![
                        &aml::CreateDWordField::new(
                            &aml::Path::new("IRQW"),
                            &aml::Arg(0),
                            &0x05_u64,
                        ),
                        &aml::Store::new(&pir, &aml::Path::new("IRQW")),
                    ],
                ),
            ],
        )
        .to_aml_bytes(sink);
    }
}

/// Length in bytes of the SSDT header. Used to calculate the offset of other
/// fields.
///
/// <https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html?highlight=ssdt#secondary-system-description-table-fields-ssdt>
const SSDT_HEADER_LEN: usize = 36;

/// Byte offset of the FWDT OperationRegion offset address field in the SSDT
/// table. This filed is updated in fwcfg.rs during table generation.
///
/// SSDT header (36 bytes) + External operation prefix (1 byte) +
/// OperationRegion prefix (1 byte) + OperationRegion name (4 bytes) +
/// OperationRegion space (1 byte) + DWordPrefix (1 byte)
///
/// <https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/20_AML_Specification/AML_Specification.html#defopregion>
pub const SSDT_FWDT_ADDR_OFFSET: usize = SSDT_HEADER_LEN + 8;

/// Number of bytes used to store the offset address value in the FWDT
/// OperationRegion. Size of a DWord.
pub const SSDT_FWDT_ADDR_LEN: usize = 4;

/// The SSDT table is an extension to DSDT table and can be used to extend
/// resources defined in the DSDT.
///
/// <https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html#secondary-system-description-table-ssdt>
pub struct Ssdt {
    /// Offset of the area reserved for the FWDT OperationRegion data in the
    /// overall ACPI tables storage.
    fwdt_offset: usize,
}

impl Ssdt {
    pub fn new(fwdt_offset: usize) -> Self {
        Self { fwdt_offset }
    }
}

// XXX(acpi): This implementation follows the original static EDK2 tables. It
//            can probably be further simplified or eliminated entirely.
// https://github.com/oxidecomputer/edk2/blob/f33871f488bfbbc080e0f7e3881e04d0db0b6367/OvmfPkg/AcpiPlatformDxe/Qemu.c#L426-L466
impl Aml for Ssdt {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        let mut ssdt = Vec::new();

        // The FWDT OperationRegion is used to pass dynamic information about
        // the instance from the platform to the virtual machine. The main
        // information provided are the 32-bit and 64-bit PCI MMIO ranges.
        //
        // On boot, the \_SB.PCI0._CRS method reads FWDT and adjusts the PCI
        // bus configuration based on the data it holds.
        //
        // XXX(acpi): This process can be removed if \_SB.PCI0._CRS returns a
        //            static ResourceTemplate that is generated with the right
        //            instance data.
        aml::OpRegion::new(
            "FWDT".into(),
            aml::OpRegionSpace::SystemMemory,
            &DWord::new(self.fwdt_offset as u32),
            &DWord::new(0x30),
        )
        .to_aml_bytes(&mut ssdt);

        // Sleep states.
        // XXX(acpi): These sleep states are kept to keep the SSDT consistent
        //            with the original static EDK2 tables. Propolis doesn't
        //            handle these state properly, so they should be removed in
        //            the future.
        //
        //            These values don't use the SleepState struct to keep the
        //            generated AML code consistent with original EDK tables.
        aml::Name::new(
            "\\_S3_".into(),
            &aml::Package::new(vec![
                &Byte::new(PM1A_CNT_SLP_TYP_S3),
                &Byte::new(0),
                &Byte::new(0),
                &Byte::new(0),
            ]),
        )
        .to_aml_bytes(&mut ssdt);

        aml::Name::new(
            "\\_S4_".into(),
            &aml::Package::new(vec![
                &Byte::new(PM1A_CNT_SLP_TYP_S4),
                &Byte::new(0),
                &Byte::new(0),
                &Byte::new(0),
            ]),
        )
        .to_aml_bytes(&mut ssdt);

        // XXX(acpi): OEM ID, table ID, and revision are kept the same as the
        //            original static EDK2 tables for consistency. They could
        //            be set to Propolis-specific values in the future.
        let mut sdt = Sdt::new(*b"SSDT", 36, 1, *b"REDHAT", *b"OVMF    ", 0x1);
        sdt.append_slice(ssdt.as_slice());
        sdt.to_aml_bytes(sink);
    }
}

// Provides consistent DWord AML values. The acpi_tables crate minimizes
// integers to the smallest word size that the number fits.
//
// XXX(acpi): Created just to keep tables consistent with the original EDK2
//            tables.
struct DWord {
    value: u32,
}

impl DWord {
    fn new(value: u32) -> Self {
        Self { value }
    }
}

impl Aml for DWord {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        sink.byte(0x0c); // DWordPrefix
        sink.dword(self.value);
    }
}

// Provides consistent Byte AML values. The acpi_tables crate minimizes
// integers to the smallest word size that the number fits.
//
// XXX(acpi): Created just to keep tables consistent with the original EDK2
//            tables.
struct Byte {
    value: u8,
}

impl Byte {
    fn new(value: u8) -> Self {
        Self { value }
    }
}

impl Aml for Byte {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        sink.byte(0x0a); // BytePrefix
        sink.byte(self.value);
    }
}

const PCI_DSM_UUID: &str = "e5c937d0-3553-4d7a-9117-ea4d19c3434d";

const PCI_HOTPLUG_EJECT_ADDR: u16 = PCI_HOTPLUG_STATUS_ADDR + 0x08;
const PCI_HOTPLUG_EJECT_LEN: u8 = 4;

const PCI_HOTPLUG_BUS_NUMBER_ADDR: u16 = PCI_HOTPLUG_EJECT_ADDR + 0x10;
const PCI_HOTPLUG_BUS_NUMBER_LEN: u8 = 8;

const PCI_HOTPLUG_SIZE: u8 = 0x0018;
const PCI_HOTPLUG_DEVICES: u8 = 32;

pub struct SsdtPciHotplug {}

impl SsdtPciHotplug {
    pub fn new() -> Self {
        Self {}
    }
}

impl Aml for SsdtPciHotplug {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        let mut table = Vec::new();

        aml::Scope::new(
            "\\_GPE".into(),
            vec![
                &aml::Name::new("_HID".into(), &"ACPI0006"),
                &aml::Method::new(
                    "_E01".into(),
                    0,
                    false,
                    vec![
                        &aml::Acquire::new("\\_SB_.PCI0.BLCK".into(), 0xffff),
                        &aml::MethodCall::new(
                            "\\_SB_.PCI0.PCNT".into(),
                            vec![],
                        ),
                        &aml::Release::new("\\_SB_.PCI0.BLCK".into()),
                    ],
                ),
            ],
        )
        .to_aml_bytes(&mut table);

        aml::Scope::new(
            "\\_SB_.PCI0".into(),
            vec![
                &aml::Device::new(
                    "PHPR".into(),
                    vec![
                        &aml::Name::new("_HID".into(), &"PNP0A06"),
                        &aml::Name::new("_UID".into(), &"PCI Hotplug resource"),
                        &aml::Name::new("_STA".into(), &0x0b_u8),
                        &aml::Name::new(
                            "_CRS".into(),
                            &aml::ResourceTemplate::new(vec![&aml::IO::new(
                                PCI_HOTPLUG_STATUS_ADDR,
                                PCI_HOTPLUG_STATUS_ADDR,
                                0x01,
                                PCI_HOTPLUG_SIZE,
                            )]),
                        ),
                    ],
                ),
                &aml::Mutex::new("BLCK".into(), 0x00),
                &aml::Name::new("BSEL".into(), &aml::ZERO),
                &aml::OpRegion::new(
                    "PCST".into(),
                    aml::OpRegionSpace::SystemIO,
                    &PCI_HOTPLUG_STATUS_ADDR,
                    &PCI_HOTPLUG_STATUS_LEN,
                ),
                &aml::Field::new(
                    "PCST".into(),
                    aml::FieldAccessType::DWord,
                    aml::FieldLockRule::NoLock,
                    aml::FieldUpdateRule::WriteAsZeroes,
                    vec![
                        aml::FieldEntry::Named(*b"PCIU", 32),
                        aml::FieldEntry::Named(*b"PCID", 32),
                    ],
                ),
                &aml::OpRegion::new(
                    "SEJ_".into(),
                    aml::OpRegionSpace::SystemIO,
                    &PCI_HOTPLUG_EJECT_ADDR,
                    &PCI_HOTPLUG_EJECT_LEN,
                ),
                &aml::Field::new(
                    "SEJ_".into(),
                    aml::FieldAccessType::DWord,
                    aml::FieldLockRule::NoLock,
                    aml::FieldUpdateRule::WriteAsZeroes,
                    vec![aml::FieldEntry::Named(*b"B0EJ", 32)],
                ),
                &aml::OpRegion::new(
                    "BNMR".into(),
                    aml::OpRegionSpace::SystemIO,
                    &PCI_HOTPLUG_BUS_NUMBER_ADDR,
                    &PCI_HOTPLUG_BUS_NUMBER_LEN,
                ),
                &aml::Field::new(
                    "BNMR".into(),
                    aml::FieldAccessType::DWord,
                    aml::FieldLockRule::NoLock,
                    aml::FieldUpdateRule::WriteAsZeroes,
                    vec![
                        aml::FieldEntry::Named(*b"BNUM", 32),
                        aml::FieldEntry::Named(*b"PIDX", 32),
                    ],
                ),
                &aml::Method::new(
                    "PCNT".into(),
                    0,
                    false,
                    vec![
                        &aml::Store::new(&aml::Path::new("BNUM"), &aml::ZERO),
                        &aml::MethodCall::new(
                            "DVNT".into(),
                            vec![&aml::Path::new("PCIU"), &aml::ONE],
                        ),
                        &aml::MethodCall::new(
                            "DVNT".into(),
                            vec![&aml::Path::new("PCID"), &0x03_u8],
                        ),
                    ],
                ),
                &PciHotplugDevices::new(PCI_HOTPLUG_DEVICES),
                &aml::Method::new(
                    "PDSM".into(),
                    5,
                    true,
                    vec![
                        &aml::If::new(
                            &aml::Equal::new(&aml::Arg(2), &aml::ZERO),
                            vec![
                                &aml::Store::new(
                                    &aml::Local(0),
                                    &aml::BufferData::new(vec![0x00]),
                                ),
                                &aml::If::new(
                                    &aml::NotEqual::new(
                                        &aml::Arg(0),
                                        &aml::Uuid::new(PCI_DSM_UUID),
                                    ),
                                    vec![&aml::Return::new(&aml::Local(0))],
                                ),
                                &aml::If::new(
                                    &aml::LessThan::new(&aml::Arg(1), &0x02_u8),
                                    vec![&aml::Return::new(&aml::Local(0))],
                                ),
                                &aml::Store::new(&aml::Local(1), &aml::ZERO),
                                &aml::Store::new(
                                    &aml::Local(2),
                                    &aml::MethodCall::new(
                                        "AIDX".into(),
                                        vec![
                                            &aml::DeRefOf::new(
                                                &aml::Index::new(
                                                    &aml::ZERO,
                                                    &aml::Arg(4),
                                                    &aml::ZERO,
                                                ),
                                            ),
                                            &aml::DeRefOf::new(
                                                &aml::Index::new(
                                                    &aml::ZERO,
                                                    &aml::Arg(4),
                                                    &aml::ONE,
                                                ),
                                            ),
                                        ],
                                    ),
                                ),
                                &aml::If::new(
                                    &aml::LogicalNot::new(&aml::Or::new(
                                        &aml::ZERO,
                                        &aml::Equal::new(
                                            &aml::Local(2),
                                            &aml::ZERO,
                                        ),
                                        &aml::Equal::new(
                                            &aml::Local(2),
                                            &0xffffffff_u32,
                                        ),
                                    )),
                                    vec![
                                        &aml::Or::new(
                                            &aml::Local(1),
                                            &aml::Local(1),
                                            &aml::ONE,
                                        ),
                                        &aml::Or::new(
                                            &aml::Local(1),
                                            &aml::Local(1),
                                            &aml::ShiftLeft::new(
                                                &aml::ZERO,
                                                &aml::ONE,
                                                &0x07_u8,
                                            ),
                                        ),
                                    ],
                                ),
                                &aml::Store::new(
                                    &aml::Index::new(
                                        &aml::ZERO,
                                        &aml::Local(0),
                                        &aml::ZERO,
                                    ),
                                    &aml::Local(1),
                                ),
                                &aml::Return::new(&aml::Local(0)),
                            ],
                        ),
                        &aml::If::new(
                            &aml::Equal::new(&aml::Arg(2), &0x07_u8),
                            vec![
                                &aml::Store::new(
                                    &aml::Local(2),
                                    &aml::MethodCall::new(
                                        "AIDX".into(),
                                        vec![
                                            &aml::DeRefOf::new(
                                                &aml::Index::new(
                                                    &aml::ZERO,
                                                    &aml::Arg(4),
                                                    &aml::ZERO,
                                                ),
                                            ),
                                            &aml::DeRefOf::new(
                                                &aml::Index::new(
                                                    &aml::ZERO,
                                                    &aml::Arg(4),
                                                    &aml::ONE,
                                                ),
                                            ),
                                        ],
                                    ),
                                ),
                                &aml::Store::new(
                                    &aml::Local(0),
                                    // TODO: make empty package
                                    &aml::Package::new(vec![
                                        &aml::ZERO,
                                        &aml::ZERO,
                                    ]),
                                ),
                                &aml::If::new(
                                    &aml::LogicalNot::new(
                                        &aml::LogicalOr::new(
                                            &aml::Equal::new(
                                                &aml::Local(2),
                                                &aml::ZERO,
                                            ),
                                            &aml::Equal::new(
                                                &aml::Local(2),
                                                &0xffffffff_u32,
                                            ),
                                        ),
                                    ),
                                    vec![
                                        &aml::Store::new(
                                            &aml::Index::new(
                                                &aml::ZERO,
                                                &aml::Local(0),
                                                &aml::ZERO,
                                            ),
                                            &aml::Local(2),
                                        ),
                                        &aml::Store::new(
                                            &aml::Index::new(
                                                &aml::ZERO,
                                                &aml::Local(0),
                                                &aml::ONE,
                                            ),
                                            &"",
                                        ),
                                    ],
                                ),
                                &aml::Return::new(&aml::Local(0)),
                            ],
                        ),
                    ],
                ),
                &aml::Method::new(
                    "AIDX".into(),
                    2,
                    false,
                    vec![
                        &aml::Acquire::new("BLCK".into(), 0xffff),
                        &aml::Store::new(&aml::Path::new("BNUM"), &aml::Arg(0)),
                        &aml::ShiftLeft::new(
                            &aml::Path::new("PIDX"),
                            &aml::ONE,
                            &aml::Arg(1),
                        ),
                        &aml::Store::new(
                            &aml::Local(0),
                            &aml::Path::new("PIDX"),
                        ),
                        &aml::Release::new("BLCK".into()),
                        &aml::Return::new(&aml::Local(0)),
                    ],
                ),
                &aml::Method::new(
                    "PCEJ".into(),
                    2,
                    false,
                    vec![
                        &aml::Acquire::new("BLCK".into(), 0xffff),
                        &aml::Store::new(&aml::Path::new("BNUM"), &aml::Arg(0)),
                        &aml::ShiftLeft::new(
                            &aml::Path::new("B0EJ"),
                            &aml::ONE,
                            &aml::Arg(1),
                        ),
                        &aml::Release::new("BLCK".into()),
                        &aml::Return::new(&aml::ZERO),
                    ],
                ),
            ],
        )
        .to_aml_bytes(&mut table);

        let mut sdt = Sdt::new(*b"SSDT", 36, 1, *b"OXIDE ", *b"PCIHPLUG", 0x1);
        sdt.append_slice(table.as_slice());
        sdt.to_aml_bytes(sink);
    }
}

struct PciHotplugDevices {
    devices: u8,
}

impl PciHotplugDevices {
    fn new(devices: u8) -> Self {
        Self { devices }
    }
}

impl Aml for PciHotplugDevices {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        let mut dvnt = Vec::new();

        for i in 3..self.devices {
            let name = format!("S{:02X}_", i * 8);
            dbg!(&name);
            PciHotplugDevice::new(name.clone(), i).to_aml_bytes(sink);
            dvnt.push(PciHotplugDeviceNotify::new(name.clone(), i));
        }

        aml::Method::new(
            "DVNT".into(),
            2,
            false,
            dvnt.iter().map(|e| e as &dyn Aml).collect(),
        )
        .to_aml_bytes(sink);
    }
}

struct PciHotplugDevice {
    name: String,
    number: u8,
}

impl PciHotplugDevice {
    fn new(name: String, number: u8) -> Self {
        Self { name, number }
    }
}

impl Aml for PciHotplugDevice {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        aml::Device::new(
            aml::Path::new(&self.name),
            vec![
                &aml::Name::new(
                    "_ADR".into(),
                    &(self.number as u32 * 0x10000_u32),
                ),
                &aml::Name::new("ASUN".into(), &self.number),
                &aml::Name::new("_SUN".into(), &self.number),
                &aml::Method::new(
                    "_DSM".into(),
                    4,
                    true,
                    vec![
                        &aml::Store::new(
                            &aml::Local(0),
                            &aml::Package::new(vec![&aml::ZERO, &aml::ZERO]),
                        ),
                        &aml::Store::new(
                            &aml::Index::new(
                                &aml::ZERO,
                                &aml::Local(0),
                                &aml::ZERO,
                            ),
                            &aml::Path::new("BSEL"),
                        ),
                        &aml::Store::new(
                            &aml::Index::new(
                                &aml::ZERO,
                                &aml::Local(0),
                                &aml::ONE,
                            ),
                            &aml::Path::new("ASUN"),
                        ),
                        &aml::Return::new(&aml::MethodCall::new(
                            "PDSM".into(),
                            vec![
                                &aml::Arg(0),
                                &aml::Arg(1),
                                &aml::Arg(2),
                                &aml::Arg(3),
                                &aml::Local(0),
                            ],
                        )),
                    ],
                ),
                &aml::Method::new(
                    "_EJ0".into(),
                    1,
                    false,
                    vec![&aml::MethodCall::new(
                        "PCEJ".into(),
                        vec![&aml::Path::new("BSEL"), &aml::Path::new("_SUN")],
                    )],
                ),
            ],
        )
        .to_aml_bytes(sink);
    }
}

struct PciHotplugDeviceNotify {
    name: String,
    number: u8,
}

impl PciHotplugDeviceNotify {
    fn new(name: String, number: u8) -> Self {
        Self { name, number }
    }
}

impl Aml for PciHotplugDeviceNotify {
    fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
        aml::If::new(
            &aml::And::new(&aml::ZERO, &aml::Arg(0), &(1_u32 << self.number)),
            vec![&aml::Notify::new(&aml::Path::new(&self.name), &aml::Arg(1))],
        )
        .to_aml_bytes(sink);
    }
}

#[cfg(test)]
mod test {
    use super::*;

    struct MockDsdtGenerator {
        scope: DsdtScope,
    }
    impl DsdtGenerator for MockDsdtGenerator {
        fn dsdt_scope(&self) -> DsdtScope {
            self.scope
        }
    }
    impl Aml for MockDsdtGenerator {
        fn to_aml_bytes(&self, sink: &mut dyn AmlSink) {
            aml::Name::new("TEST".into(), &format!("{:?}", self.scope))
                .to_aml_bytes(sink);
        }
    }

    #[test]
    fn dsdt_generator_aml() {
        let generators: Vec<&dyn DsdtGenerator> = vec![
            &MockDsdtGenerator { scope: DsdtScope::SystemBus },
            &MockDsdtGenerator { scope: DsdtScope::PciRoot },
            &MockDsdtGenerator { scope: DsdtScope::Lpc },
        ];

        let mut got = Vec::new();
        let mut expected = Vec::new();

        // Filter by SystemBus.
        DsdtGeneratorAml::new(&generators, DsdtScope::SystemBus)
            .to_aml_bytes(&mut got);
        aml::Name::new("TEST".into(), &"SystemBus").to_aml_bytes(&mut expected);
        assert_eq!(expected, got);

        got.clear();
        expected.clear();

        // Filter by PciRoot.
        DsdtGeneratorAml::new(&generators, DsdtScope::PciRoot)
            .to_aml_bytes(&mut got);
        aml::Name::new("TEST".into(), &"PciRoot").to_aml_bytes(&mut expected);
        assert_eq!(expected, got);

        got.clear();
        expected.clear();

        // Filter by Lpc.
        DsdtGeneratorAml::new(&generators, DsdtScope::Lpc)
            .to_aml_bytes(&mut got);
        aml::Name::new("TEST".into(), &"Lpc").to_aml_bytes(&mut expected);
        assert_eq!(expected, got);
    }

    #[test]
    fn dsdt_valid_aml() {
        let config = DsdtConfig {
            generators: &[
                &MockDsdtGenerator { scope: DsdtScope::SystemBus },
                &MockDsdtGenerator { scope: DsdtScope::PciRoot },
                &MockDsdtGenerator { scope: DsdtScope::Lpc },
            ],
        };
        let dsdt = Dsdt::new(config);
        let mut aml = Vec::new();
        dsdt.to_aml_bytes(&mut aml);

        // Look for key elements.
        assert!(aml.windows(4).any(|w| w == b"_SB_"));
        assert!(aml.windows(4).any(|w| w == b"PCI0"));
        assert!(aml.windows(4).any(|w| w == b"_PRT"));
        assert!(aml.windows(4).any(|w| w == b"LPC_"));
    }

    #[test]
    fn field_references() {
        let mut sink = Vec::new();

        // Validate DWord AddressSpace min, max, and len offsets.
        let min = 0xf800_0000_u32;
        let max = 0xfffb_ffff_u32;
        let len = max - min + 1;
        aml::AddressSpace::new_memory(
            aml::AddressSpaceCacheable::NotCacheable,
            true,
            min,
            max,
            None,
        )
        .to_aml_bytes(&mut sink);
        assert_eq!(
            sink[ADDRESS_SPACE_32_MIN_OFFSET
                ..(ADDRESS_SPACE_32_MIN_OFFSET + 4)],
            min.to_le_bytes()
        );
        assert_eq!(
            sink[ADDRESS_SPACE_32_MAX_OFFSET
                ..(ADDRESS_SPACE_32_MAX_OFFSET + 4)],
            max.to_le_bytes()
        );
        assert_eq!(
            sink[ADDRESS_SPACE_32_LEN_OFFSET
                ..(ADDRESS_SPACE_32_LEN_OFFSET + 4)],
            len.to_le_bytes()
        );

        sink.clear();

        // Validate QWord AddressSpace min, max, and len offsets.
        let min = 0x0080_0000_0000_u64;
        let max = 0x0fff_ffff_ffff_u64;
        let len = max - min + 1;
        aml::AddressSpace::new_memory(
            aml::AddressSpaceCacheable::Cacheable,
            true,
            min,
            max,
            None,
        )
        .to_aml_bytes(&mut sink);
        assert_eq!(
            sink[ADDRESS_SPACE_64_MIN_OFFSET
                ..(ADDRESS_SPACE_64_MIN_OFFSET + 8)],
            min.to_le_bytes()
        );
        assert_eq!(
            sink[ADDRESS_SPACE_64_MAX_OFFSET
                ..(ADDRESS_SPACE_64_MAX_OFFSET + 8)],
            max.to_le_bytes()
        );
        assert_eq!(
            sink[ADDRESS_SPACE_64_LEN_OFFSET
                ..(ADDRESS_SPACE_64_LEN_OFFSET + 8)],
            len.to_le_bytes()
        );

        sink.clear();

        // Validate Interrupt interrupt list offset.
        aml::Interrupt::new(true, false, false, true, vec![0x05])
            .to_aml_bytes(&mut sink);
        assert_eq!(
            sink[INTERRUPT_LIST_OFFSET..(INTERRUPT_LIST_OFFSET + 4)],
            0x05_u32.to_le_bytes()
        );

        sink.clear();

        // Validate FWDT offset address field offset.
        Ssdt::new(0xabc).to_aml_bytes(&mut sink);
        assert_eq!(
            sink[SSDT_FWDT_ADDR_OFFSET
                ..(SSDT_FWDT_ADDR_OFFSET + SSDT_FWDT_ADDR_LEN)],
            0xabc_u32.to_le_bytes()
        );
    }
}
