// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! ACPI table and AML bytecode generation.
//!
//! Historically, Propolis used static ACPI tables generated by EDK2. This
//! required making code changes in two separate repositories to ensure the
//! tables matched the expected hardware platform.
//!
//! Later releases of EDK2 dropped support for the built-in tables and required
//! the hypervisor to generate their own tables and load them into the guest
//! firmware using the QEMU Firmware Configuration Device (fw_cfg).
//!
//! This module contains the code that generates these ACPI tables, but it is
//! currently focused on retaining compatibility with the original static EDK2
//! tables. The original tables can be found in the EDK2 fork repository.
//!
//! https://github.com/oxidecomputer/edk2/tree/propolis/edk2-stable202105/OvmfPkg/AcpiTables

use serde::{Deserialize, Serialize};

use crate::hw::chipset::i440fx;

pub mod aml;
pub mod dsdt;
pub mod facs;
pub mod fadt;
pub mod file_sink;
pub mod madt;
pub mod rsdp;
pub mod ssdt_edk2;
pub mod xsdt;

pub use dsdt::{Dsdt, DsdtConfig, DsdtDeviceType, DsdtGenerator, DsdtScope};
pub use facs::{Facs, FacsConfig};
pub use fadt::{
    Fadt, FadtConfig, FADT_DSDT_LEN, FADT_DSDT_OFFSET, FADT_FACS_LEN,
    FADT_FACS_OFFSET, FADT_X_DSDT_LEN, FADT_X_DSDT_OFFSET,
};
pub use file_sink::FileSink;
pub use madt::{Madt, MadtConfig};
pub use rsdp::{
    Rsdp, RsdpConfig, RSDP_EXTENDED_CHECKSUM_OFFSET, RSDP_EXTENDED_TABLE_LEN,
    RSDP_V1_CHECKSUM_OFFSET, RSDP_V1_TABLE_LEN, RSDP_XSDT_ADDR_LEN,
    RSDP_XSDT_ADDR_OFFSET,
};
pub use ssdt_edk2::{SsdtEdk2, SsdtEdk2Config};
pub use xsdt::{Xsdt, XsdtConfig, XSDT_HEADER_LEN};

// Values used to reference table checksums to recompute them after values are
// changed during table generation.
pub const TABLE_HEADER_CHECKSUM_OFFSET: usize = 9;
pub const TABLE_HEADER_CHECKSUM_LEN: usize = 1;

#[derive(
    Clone, Copy, Debug, Default, Eq, PartialEq, Hash, Serialize, Deserialize,
)]
pub enum AcpiVariant {
    #[default]
    V0,
}

// Internal values shared across tables.

// Values inherited from the original EDK2 static tables. They could be set to
// Propolis-specific values in the future.
const OEM_ID: &[u8; 6] = b"OVMF  ";
const OEM_TABLE_ID: &[u8; 8] = b"OVMFEDK2";
const OEM_REVISION: u32 = 0x20130221;

// IRQs used to handle PCI interrupts.
const PCI_LINK_IRQS: [u8; 4] = [0x05, i440fx::SCI_IRQ, 0x0a, 0x0b];

// VIOAPIC_BASE in bhyve.
const IO_APIC_ADDR: u32 = 0xfec0_0000;
// VIOAPIC_SIZE in bhyve.
const IO_APIC_LEN: u32 = 0x1000;

// DEFAULT_APIC_BASE in bhyve source code.
const LOCAL_APIC_ADDR: u32 = 0xfee0_0000;
// PAGE_SIZE (4096) in bhyve, but this value was inherited from EDK2.
const LOCAL_APIC_LEN: u32 = 0x10_0000;

// Register used for PCI hotplug. This value was chosen to match QEMU and the
// original EDK2 ACPI tables.
//
// Refer to the `piix4_acpi_system_hot_add_init` function in QEMU for more
// information.
const GPE0_BLK_ADDR: u16 = 0xafe0;
const GPE0_BLK_LEN: u8 = 4;
